name: Python Application Workflow

on:
  push:
    branches:
      - staging
      - main
  release:
    types: [created]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest

  deploy-to-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to staging
      run: echo "Deploying to staging environment"
      # Add your deployment script here, e.g., bash deploy-staging.sh
      env:
        DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}

  deploy-to-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to production
      run: echo "Deploying to production environment"
      # Add your deployment script here, e.g., bash deploy-production.sh
      env:
        DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
